# UPDATE following:
#   ADMIN_EMAIL
#   ADMIN_NAME
#   ADMIN_PASSWORD
#   GATEWAY_VERSION
#   SECRET_KEY_BASE

ACTIONS:                      [map, table, chart, watch, metadata, history, update]
ADMIN_EMAIL:                  #UPDATE
ADMIN_NAME:                   #UPDATE
ADMIN_PASSWORD:               #UPDATE
APP_NAME:                     gateway-prod
DISABLE_IP_SPOOFING_CHECK:    true
GATEWAY_VERSION:              1.1.9-rc1 #UPDATE as needed
HOST:                         tig.nymtc.org ##UPDATE as needed
LOG_LEVEL:                    info
MAX_THREADS:                  "1"
MIN_THREADS:                  "1"
PUMA_WORKERS:                 "2"
RESTART_THRESHOLD:            "500"
ROLES:                        [admin, public,  contributor, agency]
SECRET_KEY_BASE:              911ead7b173d82e5bbf2e3b0a07ca12fc3cb0ebbaeda8d0e383121a509ebf9cfce36784de476cefc45187281ec80f9f01ea1e3343a4229973d6d4b59c0cc634d

production:
  DB_SCHEMA:    gateway_prod
  DB_POOL_SIZE: "5"
  DB_USER_NAME: gateway
  DB_PASSWORD:  #UPDATE
  DB_HOST:    localhost
  DB_PORT:    "5432"
